# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bentoml_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x62\x65ntoml_service.proto\x12\x07\x62\x65ntoml\"\x07\n\x05\x45mpty\"8\n\x10\x44\x61taHeadResponse\x12$\n\tdata_head\x18\x01 \x03(\x0b\x32\x11.bentoml.DataHead\"_\n\x08\x44\x61taHead\x12\'\n\x03row\x18\x01 \x03(\x0b\x32\x1a.bentoml.DataHead.RowEntry\x1a*\n\x08RowEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"*\n\x13PredictionsResponse\x12\x13\n\x0bpredictions\x18\x01 \x03(\x02\"\x1b\n\x0bRMEResponse\x12\x0c\n\x04rmse\x18\x01 \x01(\x02\"\\\n\x11InferenceResponse\x12$\n\tdata_head\x18\x01 \x03(\x0b\x32\x11.bentoml.DataHead\x12\x13\n\x0bpredictions\x18\x02 \x03(\x02\x12\x0c\n\x04rmse\x18\x03 \x01(\x02\x32\xf7\x01\n\x0e\x42\x65ntoMLService\x12\x38\n\x0bGetDataHead\x12\x0e.bentoml.Empty\x1a\x19.bentoml.DataHeadResponse\x12>\n\x0eGetPredictions\x12\x0e.bentoml.Empty\x1a\x1c.bentoml.PredictionsResponse\x12/\n\x07GetRMSE\x12\x0e.bentoml.Empty\x1a\x14.bentoml.RMEResponse\x12:\n\x0cGetInference\x12\x0e.bentoml.Empty\x1a\x1a.bentoml.InferenceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bentoml_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATAHEAD_ROWENTRY']._loaded_options = None
  _globals['_DATAHEAD_ROWENTRY']._serialized_options = b'8\001'
  _globals['_EMPTY']._serialized_start=34
  _globals['_EMPTY']._serialized_end=41
  _globals['_DATAHEADRESPONSE']._serialized_start=43
  _globals['_DATAHEADRESPONSE']._serialized_end=99
  _globals['_DATAHEAD']._serialized_start=101
  _globals['_DATAHEAD']._serialized_end=196
  _globals['_DATAHEAD_ROWENTRY']._serialized_start=154
  _globals['_DATAHEAD_ROWENTRY']._serialized_end=196
  _globals['_PREDICTIONSRESPONSE']._serialized_start=198
  _globals['_PREDICTIONSRESPONSE']._serialized_end=240
  _globals['_RMERESPONSE']._serialized_start=242
  _globals['_RMERESPONSE']._serialized_end=269
  _globals['_INFERENCERESPONSE']._serialized_start=271
  _globals['_INFERENCERESPONSE']._serialized_end=363
  _globals['_BENTOMLSERVICE']._serialized_start=366
  _globals['_BENTOMLSERVICE']._serialized_end=613
# @@protoc_insertion_point(module_scope)
